let firstName = 'Keyosha';
let lastName = 'Waugh';
let age = 29;
let address = '33 16th Ave E';
let dateOfBirth = '15/04/1990';
console.log('address: ', address);
console.log('lastName: ', lastName);
console.log('dateOfBirth', dateOfBirth);
console.log('firstName: ', firstName);
console.log('age: ', age);